name : "Enter your name"
email : "Enter your email"
tel : "Enter your tel"
address : "Enter your adrress"
aptEtc : ""
zip : "Enter your zip code"
city : "Enter your city"
cityAbbrev : "Enter your city abbreviation"
countryAbbrev : "USA"
creditCardNumber : "Enter your credit card number"
cardExpireMonth : "Enter your expired month"
cardExpireYear : "Enter your expired year"
CVV : "Enter your cvv"
keyWords:
  - "xXKHM2fxoAw"
dropTime:  "2018-05-10 11:00:00"